<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>38. Count And Say — CFML Solution</title>
    <link rel="stylesheet" href="/css/theme.css">
</head>
<body>
<cfinclude template="/includes/header.cfm">
<main>
<cfscript>
/**
 * Count and Say - LeetCode Problem #38
 *
 * The count-and-say sequence: each term is generated by reading the previous term.
 * Given an integer n (1 <= n <= 30), return the nth term.
 *
 * @param n Term number
 * @return nth term of the count-and-say sequence
 */
function countAndSay(required numeric n) {
	var current = "1";

	for (var i = 2; i <= n; i++) {
		var next = "";
		var j = 1;
		var len = len(current);

		while (j <= len) {
			var ch = mid(current, j, 1);
			var count = 1;

			while (j + count <= len && mid(current, j + count, 1) == ch) {
				count++;
			}

			next &= count & ch;
			j += count;
		}

		current = next;
	}

	return current;
}

function runTests() {
	writeOutput("<h2>Count and Say - Test Results</h2>");

	var r1 = countAndSay(1);
	writeOutput("<p><strong>Test 1:</strong> n=1</p>");
	writeOutput("<p>Expected: ""1"", Got: """ & r1 & """</p>");
	writeOutput("<p>Status: " & (r1 == "1" ? "PASS" : "FAIL") & "</p><br>");

	var r2 = countAndSay(4);
	writeOutput("<p><strong>Test 2:</strong> n=4</p>");
	writeOutput("<p>Expected: ""1211"", Got: """ & r2 & """</p>");
	writeOutput("<p>Status: " & (r2 == "1211" ? "PASS" : "FAIL") & "</p><br>");

	var r3 = countAndSay(5);
	writeOutput("<p><strong>Test 3:</strong> n=5</p>");
	writeOutput("<p>Expected: ""111221"", Got: """ & r3 & """</p>");
	writeOutput("<p>Status: " & (r3 == "111221" ? "PASS" : "FAIL") & "</p><br>");

	var r4 = countAndSay(6);
	writeOutput("<p><strong>Test 4:</strong> n=6</p>");
	writeOutput("<p>Expected: ""312211"", Got: """ & r4 & """</p>");
	writeOutput("<p>Status: " & (r4 == "312211" ? "PASS" : "FAIL") & "</p><br>");
}

runTests();
</cfscript>
</main>
<cfinclude template="/includes/footer.cfm">
</body>
</html>
